apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubernetesdummyapi-pvc
spec:
  accessModes:
    - ReadWriteMany
    # - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 100M