apiVersion: v1
kind: Service
metadata:
  name: kubernetesdummyapi-service
spec:
  selector:
    app: kubernetesdummyapi-simple
  type: ClusterIP
  ports:
    - name: kubernetesdummyapi-port
      port: 8080
      targetPort: 80